# Generated by Django 5.0 on 2024-07-03 12:20

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
