# Generated by Django 5.0 on 2024-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0002_addEmailColumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
