# Generated by Django 5.0 on 2024-07-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0004_countries_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Country',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpCountry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.countries'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.departments'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
