# Generated by Django 4.2.13 on 2024-07-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0006_alter_employee_empcountry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.countries')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('state', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state')),
            ],
        ),
    ]
