# Generated by Django 4.2.13 on 2024-07-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0007_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.city')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.countries')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.state')),
            ],
        ),
    ]
