# Generated by Django 4.2.13 on 2024-07-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsertMultipleEmployees',
            new_name='EmployeesInfo',
        ),
    ]
